# For more information, please refer to https://aka.ms/vscode-docker-python
FROM mcr.microsoft.com/vscode/devcontainers/python:3.9
RUN pip install --upgrade pip
RUN pip install poetry
#RUN poetry install
